version: '3.8'

# Persistence data
volumes:
  mongodata:


services:

  #container mongo
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
    - "27018:27018"
    volumes:
    - mongodata:/data
    - ./datascript:/datascript
    environment:
      TZ: UTC
      MONGO_INITDB_ROOT_USERNAME: ern
      MONGO_INITDB_ROOT_PASSWORD: ern2024