version: '3.8'

# Persistence data
volumes:
  mongodata:


services:

  #container mongo
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - mongodata:/data
    - ./datascript:/datascript
    command: mongod --bind_ip_all